name: Run specs

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run specs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Run rspec
      run: bundle exec rspec
